### PR TITLE
[BALANCE] Cloning Debuff

### PR DESCRIPTION
**Pull request by HellCatten**
# Cloning debuff

Добавлены дебаффы на человека после клонирования:
- Дебафф голода, жажды и опьянения.

---

# Изменения

:cl: Hell_Cat
- add: Дебаффы после клонирования.

### CODE REVIEW

**Comment by VMSolidus** [comment]
I actually have a pretty comprehensive update to cloning on Upstream, although it's stuck in review hell even after I accepted and made changes from my Maintainers requests.

https://github.com/Simple-Station/Einstein-Engines/pull/735

**Comment by Remuchi** [comment]
> I actually have a pretty comprehensive update to cloning on Upstream, although it's stuck in review hell even after I accepted and made changes from my Maintainers requests.
> 
> [Simple-Station/Einstein-Engines#735](https://github.com/Simple-Station/Einstein-Engines/pull/735)

I don't think your refactor applies hunger and thirst after cloning is done?

**Comment by HellCatten** [comment]
> > I actually have a pretty comprehensive update to cloning on Upstream, although it's stuck in review hell even after I accepted and made changes from my Maintainers requests.
> > [Simple-Station/Einstein-Engines#735](https://github.com/Simple-Station/Einstein-Engines/pull/735)
> 
> I don't think your refactor applies hunger and thirst after cloning is done?

I think it's better to wait for VSSolidus's cloning update. It's more important than some balance/debuff stuff in 10 lines.

**Comment by VMSolidus** [comment]
> > I actually have a pretty comprehensive update to cloning on Upstream, although it's stuck in review hell even after I accepted and made changes from my Maintainers requests.
> > [Simple-Station/Einstein-Engines#735](https://github.com/Simple-Station/Einstein-Engines/pull/735)
> 
> I don't think your refactor applies hunger and thirst after cloning is done?

I can probably combine this into the cloning update.

**Comment by VMSolidus** [comment]
> > I actually have a pretty comprehensive update to cloning on Upstream, although it's stuck in review hell even after I accepted and made changes from my Maintainers requests.
> > [Simple-Station/Einstein-Engines#735](https://github.com/Simple-Station/Einstein-Engines/pull/735)
> 
> I don't think your refactor applies hunger and thirst after cloning is done?

I actually just implemented your hunger and thirst modifiers into the cloning refactor. I set it up so that hunger and thirst are modified by an amount defined in the Clone Pod Component.

**Comment by Remuchi** [comment]
Closed since a more complex system is already in development

**Pull request closed without merging**
